import java.awt.EventQueue;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Represents a class for adding new flight records to a database.
 * This class allows airline staff to input flight details, such as flight ID,
 * name, source, departure,
 * departure time, arrival time, and flight charge, and stores them in a
 * database.
 *
 * @author Imaan Ibrar
 * @version 2.0
 * @since 2022-06-20
 */
public class addflight extends javax.swing.JFrame {

        // Variables for database connection and prepared statement.
        Connection con;
        PreparedStatement pst;

        /**
         * Creates new form addflight
         */
        public addflight() {
                getContentPane().setBackground(new Color(162, 201, 201));
                initComponents();
                autoID();
                setExtendedState(JFrame.MAXIMIZED_BOTH);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panel1 = new javax.swing.JPanel();
                flightIdLabel = new javax.swing.JLabel();
                flightIdText = new javax.swing.JLabel();
                flightNameLabel = new javax.swing.JLabel();
                sourceLabel = new javax.swing.JLabel();
                departureLabel = new javax.swing.JLabel();
                flightNameText = new javax.swing.JTextField();
                departureTimeLabel = new javax.swing.JLabel();
                departureTimeText = new javax.swing.JTextField();
                arrivalTimeText = new javax.swing.JTextField();
                arrivalTimeLabel = new javax.swing.JLabel();
                flightChargeLabel = new javax.swing.JLabel();
                flightChargeText = new javax.swing.JTextField();
                AddBtn = new javax.swing.JButton();
                BackBtn = new javax.swing.JButton();
                sourceText = new javax.swing.JComboBox<>();
                departuretext = new javax.swing.JComboBox<>();
                panel3 = new javax.swing.JPanel();
                contactUsLabel = new javax.swing.JLabel();
                numberLabel = new javax.swing.JLabel();
                backgroudAdjustLabel2 = new javax.swing.JLabel();
                backgroundAdjustLabel1 = new javax.swing.JLabel();
                jskyIcon = new javax.swing.JLabel();
                instaIcon = new javax.swing.JLabel();
                linkedInIcon = new javax.swing.JLabel();
                warningDepartureTime = new javax.swing.JLabel();
                warningArrivalTime = new javax.swing.JLabel();
                warningFlightCharge = new javax.swing.JLabel();
                panel2 = new javax.swing.JPanel();
                addFlightLabel = new javax.swing.JLabel();

                panel1.setBackground(new java.awt.Color(162, 201, 201));

                flightIdLabel.setFont(new Font("Tahoma", Font.BOLD, 25)); // NOI18N
                flightIdLabel.setText("Flight ID");

                flightIdText.setFont(new Font("Tahoma", Font.BOLD, 20)); // NOI18N
                flightIdText.setForeground(new java.awt.Color(153, 153, 153));
                flightIdText.setText("Flight ID");

                flightNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                flightNameLabel.setText("Flight Name");

                sourceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                sourceLabel.setText("Source");

                departureLabel.setBackground(new java.awt.Color(0, 0, 0));
                departureLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                departureLabel.setText("Departure");

                // jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                // jLabel6.setText("Date");

                departureTimeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                departureTimeLabel.setText("Departure Time");

                departureTimeText.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtdtimeActionPerformed(evt);
                        }
                });
                departureTimeText.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                txtdtimeKeyReleased(evt);
                        }
                });

                arrivalTimeText.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtarrtimeActionPerformed(evt);
                        }
                });
                arrivalTimeText.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                txtarrtimeKeyReleased(evt);
                        }
                });

                arrivalTimeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                arrivalTimeLabel.setText("Arrival Time");

                flightChargeLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                flightChargeLabel.setText("Flight Charge");

                flightChargeText.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtflightchargeActionPerformed(evt);
                        }
                });
                flightChargeText.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                txtflightchargeKeyReleased(evt);
                        }
                });

                AddBtn.setBackground(new java.awt.Color(0, 51, 51));
                AddBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                AddBtn.setForeground(new java.awt.Color(255, 255, 255));
                AddBtn.setText("Add");
                AddBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                AddBtnAction(evt);
                        }
                });

                BackBtn.setBackground(new java.awt.Color(0, 51, 51));
                BackBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                BackBtn.setForeground(new java.awt.Color(255, 255, 255));
                BackBtn.setText("Back");
                BackBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                backBtnAction(evt);
                        }
                });

                sourceText.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Pakistan", "Srilanka", "Uk", "Usa", "Canada", "China" }));

                departuretext.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Pakistan", "Srilanka", "Uk", "Usa", "Canada", "China" }));

                panel3.setBackground(new java.awt.Color(0, 102, 102));

                contactUsLabel.setFont(new Font("Segoe UI", Font.BOLD, 20)); // NOI18N
                contactUsLabel.setForeground(new java.awt.Color(255, 255, 255));
                contactUsLabel.setText("CONTACT US");
                contactUsLabel.setToolTipText("");

                numberLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
                numberLabel.setForeground(new java.awt.Color(255, 255, 255));
                numberLabel.setText("+51 789543");

                jskyIcon.setIcon(
                                new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2022-07-06 000042.png"))); // NOI18N

                instaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insta.png"))); // NOI18N

                linkedInIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/twit.png"))); // NOI18N

                javax.swing.GroupLayout groupLayoutPanel3 = new javax.swing.GroupLayout(panel3);
                groupLayoutPanel3.setHorizontalGroup(
                                groupLayoutPanel3.createParallelGroup(Alignment.TRAILING)
                                                .addGroup(groupLayoutPanel3.createSequentialGroup()
                                                                .addComponent(backgroundAdjustLabel1)
                                                                .addGap(203))
                                                .addGroup(groupLayoutPanel3.createSequentialGroup()
                                                                .addGap(19)
                                                                .addGroup(groupLayoutPanel3
                                                                                .createParallelGroup(Alignment.LEADING)
                                                                                .addGroup(groupLayoutPanel3
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(numberLabel)
                                                                                                .addPreferredGap(
                                                                                                                ComponentPlacement.RELATED,
                                                                                                                784,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(backgroudAdjustLabel2)
                                                                                                .addGap(313))
                                                                                .addGroup(groupLayoutPanel3
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(contactUsLabel,
                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                169,
                                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                                ComponentPlacement.RELATED)))
                                                                .addComponent(linkedInIcon)
                                                                .addPreferredGap(ComponentPlacement.UNRELATED)
                                                                .addComponent(instaIcon)
                                                                .addGap(43)
                                                                .addComponent(jskyIcon)
                                                                .addGap(24)));
                groupLayoutPanel3.setVerticalGroup(
                                groupLayoutPanel3.createParallelGroup(Alignment.LEADING)
                                                .addGroup(groupLayoutPanel3.createSequentialGroup()
                                                                .addGroup(groupLayoutPanel3
                                                                                .createParallelGroup(Alignment.LEADING)
                                                                                .addGroup(groupLayoutPanel3
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(backgroudAdjustLabel2)
                                                                                                .addPreferredGap(
                                                                                                                ComponentPlacement.RELATED)
                                                                                                .addComponent(contactUsLabel)
                                                                                                .addPreferredGap(
                                                                                                                ComponentPlacement.RELATED)
                                                                                                .addComponent(numberLabel))
                                                                                .addGroup(groupLayoutPanel3
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(backgroundAdjustLabel1)
                                                                                                .addGap(23)
                                                                                                .addGroup(groupLayoutPanel3
                                                                                                                .createParallelGroup(
                                                                                                                                Alignment.TRAILING)
                                                                                                                .addComponent(instaIcon)
                                                                                                                .addComponent(linkedInIcon)
                                                                                                                .addComponent(jskyIcon))))
                                                                .addContainerGap(22, Short.MAX_VALUE)));
                panel3.setLayout(groupLayoutPanel3);

                warningDepartureTime.setFont(new Font("Segoe UI", Font.BOLD, 14)); // NOI18N
                warningDepartureTime.setForeground(new java.awt.Color(204, 0, 51));
                // dtlab.setText("jLabel12");

                warningArrivalTime.setFont(new Font("Segoe UI", Font.BOLD, 14)); // NOI18N
                warningArrivalTime.setForeground(new java.awt.Color(204, 0, 51));
                // atlab.setText("jLabel12");

                warningFlightCharge.setFont(new Font("Segoe UI", Font.BOLD, 14)); // NOI18N
                warningFlightCharge.setForeground(new java.awt.Color(204, 0, 51));
                // fclab.setText("jLabel12");

                javax.swing.GroupLayout groupLayoutPanel1 = new javax.swing.GroupLayout(panel1);
                groupLayoutPanel1.setHorizontalGroup(
                                groupLayoutPanel1.createParallelGroup(Alignment.LEADING)
                                                .addGroup(groupLayoutPanel1.createSequentialGroup()
                                                                .addGroup(groupLayoutPanel1
                                                                                .createParallelGroup(Alignment.TRAILING)
                                                                                .addGroup(groupLayoutPanel1
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap(113,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addGroup(groupLayoutPanel1
                                                                                                                .createParallelGroup(
                                                                                                                                Alignment.LEADING)
                                                                                                                .addGroup(groupLayoutPanel1
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGroup(groupLayoutPanel1
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                Alignment.LEADING)
                                                                                                                                                .addGroup(groupLayoutPanel1
                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                Alignment.TRAILING)
                                                                                                                                                                .addGroup(groupLayoutPanel1
                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                .addGroup(groupLayoutPanel1
                                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                                Alignment.LEADING)
                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                departureLabel)
                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                sourceLabel)
                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                arrivalTimeLabel))
                                                                                                                                                                                .addGap(64))
                                                                                                                                                                .addGroup(groupLayoutPanel1
                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                .addComponent(flightNameLabel)
                                                                                                                                                                                .addGap(61)))
                                                                                                                                                .addComponent(departureTimeLabel))
                                                                                                                                .addGap(41)
                                                                                                                                .addGroup(groupLayoutPanel1
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                Alignment.LEADING)
                                                                                                                                                .addComponent(flightNameText,
                                                                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                136,
                                                                                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(sourceText,
                                                                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                136,
                                                                                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(departuretext,
                                                                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                136,
                                                                                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addGroup(groupLayoutPanel1
                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                .addGroup(groupLayoutPanel1
                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                Alignment.LEADING,
                                                                                                                                                                                                false)
                                                                                                                                                                                .addComponent(departureTimeText,
                                                                                                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                187,
                                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                                .addComponent(flightChargeText,
                                                                                                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                172,
                                                                                                                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                .addComponent(arrivalTimeText))
                                                                                                                                                                .addGap(38)
                                                                                                                                                                .addGroup(groupLayoutPanel1
                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                Alignment.LEADING)
                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                warningFlightCharge,
                                                                                                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                213,
                                                                                                                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                .addGroup(groupLayoutPanel1
                                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                                Alignment.LEADING)
                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                warningArrivalTime,
                                                                                                                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                213,
                                                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                warningDepartureTime,
                                                                                                                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                118,
                                                                                                                                                                                                                GroupLayout.PREFERRED_SIZE))))))
                                                                                                                .addGroup(groupLayoutPanel1
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addComponent(flightIdLabel)
                                                                                                                                .addGap(63)
                                                                                                                                .addComponent(flightIdText))
                                                                                                                .addComponent(flightChargeLabel)))
                                                                                .addGroup(groupLayoutPanel1
                                                                                                .createSequentialGroup()
                                                                                                .addGap(622)
                                                                                                .addComponent(AddBtn,
                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                117,
                                                                                                                GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(31)
                                                                .addComponent(BackBtn, GroupLayout.PREFERRED_SIZE, 110,
                                                                                GroupLayout.PREFERRED_SIZE)
                                                                .addGap(858))
                                                .addGroup(groupLayoutPanel1.createSequentialGroup()
                                                                .addComponent(panel3, GroupLayout.DEFAULT_SIZE, 1728,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap()));
                groupLayoutPanel1.setVerticalGroup(
                                groupLayoutPanel1.createParallelGroup(Alignment.LEADING)
                                                .addGroup(groupLayoutPanel1.createSequentialGroup()
                                                                .addGap(35)
                                                                .addGroup(groupLayoutPanel1
                                                                                .createParallelGroup(Alignment.BASELINE)
                                                                                .addComponent(flightIdLabel)
                                                                                .addComponent(flightIdText))
                                                                .addGap(46)
                                                                .addGroup(groupLayoutPanel1
                                                                                .createParallelGroup(Alignment.LEADING)
                                                                                .addGroup(groupLayoutPanel1
                                                                                                .createSequentialGroup()
                                                                                                .addPreferredGap(
                                                                                                                ComponentPlacement.RELATED)
                                                                                                .addGroup(groupLayoutPanel1
                                                                                                                .createParallelGroup(
                                                                                                                                Alignment.BASELINE)
                                                                                                                .addComponent(flightNameLabel)
                                                                                                                .addComponent(flightNameText,
                                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                                GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(18)
                                                                                                .addGroup(groupLayoutPanel1
                                                                                                                .createParallelGroup(
                                                                                                                                Alignment.BASELINE)
                                                                                                                .addComponent(sourceText,
                                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(sourceLabel))
                                                                                                .addGap(18)
                                                                                                .addComponent(departuretext,
                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(groupLayoutPanel1
                                                                                                .createSequentialGroup()
                                                                                                .addGap(76)
                                                                                                .addComponent(departureLabel)))
                                                                .addGap(18)
                                                                .addGroup(groupLayoutPanel1
                                                                                .createParallelGroup(Alignment.LEADING)
                                                                                .addGroup(groupLayoutPanel1
                                                                                                .createParallelGroup(
                                                                                                                Alignment.BASELINE)
                                                                                                .addComponent(departureTimeText,
                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(warningDepartureTime,
                                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                                22,
                                                                                                                GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(departureTimeLabel))
                                                                .addGap(21)
                                                                .addGroup(groupLayoutPanel1
                                                                                .createParallelGroup(Alignment.BASELINE)
                                                                                .addComponent(arrivalTimeLabel)
                                                                                .addComponent(arrivalTimeText,
                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(warningArrivalTime,
                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                22,
                                                                                                GroupLayout.PREFERRED_SIZE))
                                                                .addGap(42)
                                                                .addGroup(groupLayoutPanel1
                                                                                .createParallelGroup(Alignment.BASELINE)
                                                                                .addComponent(flightChargeLabel)
                                                                                .addComponent(flightChargeText,
                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(warningFlightCharge,
                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                22,
                                                                                                GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(ComponentPlacement.RELATED,
                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(groupLayoutPanel1
                                                                                .createParallelGroup(Alignment.BASELINE)
                                                                                .addComponent(BackBtn,
                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                46,
                                                                                                GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(AddBtn,
                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                46,
                                                                                                GroupLayout.PREFERRED_SIZE))
                                                                .addGap(124)
                                                                .addComponent(panel3, GroupLayout.PREFERRED_SIZE, 172,
                                                                                GroupLayout.PREFERRED_SIZE)));
                panel1.setLayout(groupLayoutPanel1);

                panel2.setBackground(new java.awt.Color(0, 102, 102));

                addFlightLabel.setFont(new Font("Segoe UI", Font.BOLD, 35)); // NOI18N
                addFlightLabel.setForeground(new java.awt.Color(255, 255, 255));
                addFlightLabel.setText("ADD FLIGHT");

                javax.swing.GroupLayout groupLayoutPanel2 = new javax.swing.GroupLayout(panel2);
                groupLayoutPanel2.setHorizontalGroup(
                                groupLayoutPanel2.createParallelGroup(Alignment.TRAILING)
                                                .addGroup(Alignment.LEADING, groupLayoutPanel2.createSequentialGroup()
                                                                .addGap(666)
                                                                .addComponent(addFlightLabel)
                                                                .addContainerGap(673, Short.MAX_VALUE)));
                groupLayoutPanel2.setVerticalGroup(
                                groupLayoutPanel2.createParallelGroup(Alignment.LEADING)
                                                .addGroup(Alignment.TRAILING, groupLayoutPanel2.createSequentialGroup()
                                                                .addContainerGap(47, Short.MAX_VALUE)
                                                                .addComponent(addFlightLabel)
                                                                .addGap(43)));
                panel2.setLayout(groupLayoutPanel2);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                layout.setHorizontalGroup(
                                layout.createParallelGroup(Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(Alignment.LEADING)
                                                                                .addComponent(panel2,
                                                                                                GroupLayout.DEFAULT_SIZE,
                                                                                                1545, Short.MAX_VALUE)
                                                                                .addComponent(panel1,
                                                                                                GroupLayout.PREFERRED_SIZE,
                                                                                                1545,
                                                                                                GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap()));
                layout.setVerticalGroup(
                                layout.createParallelGroup(Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(panel2, GroupLayout.PREFERRED_SIZE, 137,
                                                                                GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(ComponentPlacement.RELATED)
                                                                .addComponent(panel1, GroupLayout.DEFAULT_SIZE, 702,
                                                                                Short.MAX_VALUE)));
                getContentPane().setLayout(layout);
                sourceText.addActionListener(e -> updateDestinationDropdown());

                pack();
        }// </editor-fold>//GEN-END:initComponents\

        private void updateDestinationDropdown() {
                // Get the selected source from the sourceText dropdown
                String selectedSource = sourceText.getSelectedItem().toString();

                // Remove the selected source from the destinationText dropdown
                DefaultComboBoxModel<String> destinationModel = new DefaultComboBoxModel<>();
                for (int i = 0; i < sourceText.getItemCount(); i++) {
                        String item = sourceText.getItemAt(i).toString();
                        if (!item.equals(selectedSource)) {
                                destinationModel.addElement(item);
                        }
                }
                departuretext.setModel(destinationModel);
        }

        /**
         * Auto-generates a unique Flight ID and sets it in the "txtflightid" label.
         */
        public void autoID() {
                try {
                        con = connectionManager.getConnection();

                        // Create a statement and execute a query to get the maximum Flight ID.
                        Statement s = con.createStatement();
                        ResultSet rs = s.executeQuery("select MAX(id) from flight");
                        rs.next();
                        rs.getString("MAX(id)");

                        // If no existing Flight IDs, set the initial ID to "FO001"; otherwise,
                        // auto-generate the next ID.
                        if (rs.getString("MAX(id)") == null) {
                                flightIdText.setText("FO001");
                        } else {
                                long id = Long.parseLong(
                                                rs.getString("MAX(id)").substring(2, rs.getString("MAX(id)").length()));
                                id++;
                                flightIdText.setText("FO" + String.format("%03d", id));
                        }
                } catch (SQLException ex) {
                        Logger.getLogger(addCustomer.class.getName()).log(Level.SEVERE, null, ex);
                }

        }

        /**
         * Action performed when the "Add" button is clicked.
         * This method retrieves information from the input fields, validates the data,
         * and inserts a new flight record into the database.
         *
         * @param evt ActionEvent object representing the button click event.
         * @throws ClassNotFoundException If the MySQL JDBC driver is not found.
         * @throws SQLException           If a SQL exception occurs while interacting
         *                                with the database.
         */
        private void AddBtnAction(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AddBtnAction

                String id = flightIdText.getText();
                String flightname = flightNameText.getText();

                String source = sourceText.getSelectedItem().toString().trim();
                String depart = departuretext.getSelectedItem().toString().trim();

                String departtime = departureTimeText.getText();
                String arrtime = arrivalTimeText.getText();
                String flightcharge = flightChargeText.getText();

                int fc = Integer.parseInt(flightcharge);
                if (flightname.equals("") || departtime.equals("") || arrtime.equals("") || flightcharge.equals("")) {
                        JOptionPane.showMessageDialog(this, "Please enter the missing fields");
                } else if (departtime.equals(arrtime) || !departtime.matches("^(2[0-3]|[01]?[0-9]):([0-5]?[0-9])$")) {
                        JOptionPane.showMessageDialog(this, "Please enter wisely");

                }

                else if (arrtime.equals(departtime) || !arrtime.matches("^(2[0-3]|[01]?[0-9]):([0-5]?[0-9])$")) {
                        JOptionPane.showMessageDialog(this, "Please enter wisely");
                } else if (source.equals(depart) || depart.equals(source)) {
                        JOptionPane.showMessageDialog(this, "Source and Arrival cannot be same");
                } else if (fc < 15000 || fc > 200000) {
                        JOptionPane.showMessageDialog(this, "Invalid Charges");
                }

                else {
                        try {
                                con = connectionManager.getConnection();
                                pst = con.prepareStatement(
                                                "insert into flight(id,flightname,source,depart,deptime,arrtime,flightcharge)values(?,?,?,?,?,?,?)");

                                pst.setString(1, id);
                                pst.setString(2, flightname);
                                pst.setString(3, source);
                                pst.setString(4, depart);
                                pst.setString(5, departtime);
                                pst.setString(6, arrtime);
                                pst.setString(7, flightcharge);

                                pst.executeUpdate();

                                JOptionPane.showMessageDialog(null, "Flight Created");
                                AddBtn.setEnabled(false);
                        } catch (SQLException ex) {
                                Logger.getLogger(addflight.class.getName()).log(Level.SEVERE, null, ex);
                        }
                }
        }// GEN-LAST:event_AddBtnAction

        /**
         * Action performed when the "Back" button is clicked.
         * This method closes the current window and returns to the admin domain window.
         */
        private void backBtnAction(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backBtnAction
                this.dispose();
                adminDomainObj = new admindomain();
                adminDomainObj.setVisible(true);
        }// GEN-LAST:event_backBtnAction

        private void txtdtimeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtdtimeActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txtdtimeActionPerformed

        private void txtarrtimeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtarrtimeActionPerformed
                // TODO add your handling code here
        }// GEN-LAST:event_txtarrtimeActionPerformed

        /**
         * Action performed when the departure time field is modified.
         * This method checks if the departure time is in the correct format.
         *
         * @param evt KeyEvent object representing the key release event on the
         *            departure time field.
         */
        private void txtdtimeKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtdtimeKeyReleased
                // TODO add your handling code here:
                String regex = "^(2[0-3]|[01]?[0-9]):([0-5]?[0-9])$";
                Pattern patt = Pattern.compile(regex);
                Matcher match = patt.matcher(departureTimeText.getText());
                if (!match.matches()) {
                        warningDepartureTime.setText("Format: XX:XX");
                } else {
                        warningDepartureTime.setText(null);

                }
        }// GEN-LAST:event_txtdtimeKeyReleased

        /**
         * Action performed when the arrival time field is modified.
         * This method checks if the arrival time is in the correct format.
         *
         * @param evt KeyEvent object representing the key release event on the arrival
         *            time field.
         */
        private void txtarrtimeKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtarrtimeKeyReleased
                // TODO add your handling code here:
                String regex = "^(2[0-3]|[01]?[0-9]):([0-5]?[0-9])$";
                Pattern patt = Pattern.compile(regex);
                Matcher match = patt.matcher(arrivalTimeText.getText());
                if (!match.matches()) {
                        warningArrivalTime.setText("Format: XX:XX ");
                } else {
                        warningArrivalTime.setText(null);

                }
        }// GEN-LAST:event_txtarrtimeKeyReleased

        private void txtflightchargeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtflightchargeActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txtflightchargeActionPerformed

        /**
         * Action performed when the flight charge field is modified.
         * This method checks if the flight charge is in the correct format.
         *
         * @param evt KeyEvent object representing the key release event on the flight
         *            charge field.
         */
        private void txtflightchargeKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtflightchargeKeyReleased
                // TODO add your handling code here:
                String regex = "^[0-9]{5,6}$";
                Pattern patt = Pattern.compile(regex);
                Matcher match = patt.matcher(flightChargeText.getText());
                if (!match.matches()) {
                        warningFlightCharge.setText("Min: 15000\n Max:200000");
                } else {
                        warningFlightCharge.setText(null);

                }
        }// GEN-LAST:event_txtflightchargeKeyReleased

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel warningArrivalTime;
        private javax.swing.JLabel warningDepartureTime;
        private javax.swing.JLabel warningFlightCharge;
        private javax.swing.JButton AddBtn;
        private javax.swing.JButton BackBtn;
        private javax.swing.JLabel flightIdLabel;
        private javax.swing.JLabel addFlightLabel;
        private javax.swing.JLabel contactUsLabel;
        private javax.swing.JLabel backgroudAdjustLabel2;
        private javax.swing.JLabel numberLabel;
        private javax.swing.JLabel backgroundAdjustLabel1;
        private javax.swing.JLabel jskyIcon;
        private javax.swing.JLabel instaIcon;
        private javax.swing.JLabel linkedInIcon;
        private javax.swing.JLabel flightNameLabel;
        private javax.swing.JLabel sourceLabel;
        private javax.swing.JLabel departureLabel;
        private javax.swing.JLabel departureTimeLabel;
        private javax.swing.JLabel arrivalTimeLabel;
        private javax.swing.JLabel flightChargeLabel;
        private javax.swing.JPanel panel1;
        private javax.swing.JPanel panel2;
        private javax.swing.JPanel panel3;
        private javax.swing.JTextField arrivalTimeText;
        private javax.swing.JComboBox<String> departuretext;
        private javax.swing.JTextField departureTimeText;
        private javax.swing.JTextField flightChargeText;
        private javax.swing.JLabel flightIdText;
        private javax.swing.JTextField flightNameText;
        private javax.swing.JComboBox<String> sourceText;
        private admindomain adminDomainObj;
        // End of variables declaration//GEN-END:variables
}