/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JFrame;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.JTextArea;
import javax.swing.DropMode;
/**
 * Represents the customer domain window of the application.
 * Provides options for customers to perform various actions such as making a booking,
 * registering, updating and canceling a booking, viewing a ticket, and navigating to the main menu.
 * Constantly monitored by the main server.
 *
 * @author laiba atiq
 * @version 1.0
 * @since 2023-11-21
 */
public class cusdomain extends javax.swing.JFrame {
	
    /**
     * Creates new form cusdomain
     */
    public cusdomain() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setVerticalAlignment(SwingConstants.TOP);
        jLabel5 = new javax.swing.JLabel();
        jButton6=new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        
        JLabel Company_name = new JLabel("JSKY ");
        Company_name.setForeground(new Color(255, 255, 255));
        Company_name.setFont(new Font("Tahoma", Font.BOLD, 40));
        
        JLabel logoslogan = new JLabel("Travel in Style");
        logoslogan.setFont(new Font("Tahoma", Font.PLAIN, 15));
        logoslogan.setForeground(new Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(29)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(logoslogan, GroupLayout.PREFERRED_SIZE, 139, GroupLayout.PREFERRED_SIZE)
        				.addComponent(Company_name, GroupLayout.PREFERRED_SIZE, 128, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 1245, Short.MAX_VALUE)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 86, GroupLayout.PREFERRED_SIZE)
        			.addGap(41))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(24)
        			.addComponent(Company_name, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(logoslogan)
        			.addContainerGap(22, Short.MAX_VALUE))
        		.addGroup(Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        			.addContainerGap(34, Short.MAX_VALUE)
        			.addComponent(jLabel1)
        			.addContainerGap())
        );
        jPanel2.setLayout(jPanel2Layout);

        jPanel4.setBackground(new java.awt.Color(151, 190, 190));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5Layout.setHorizontalGroup(
        	jPanel5Layout.createParallelGroup(Alignment.TRAILING)
        		.addGap(0, 1514, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
        	jPanel5Layout.createParallelGroup(Alignment.TRAILING)
        		.addGap(0, 86, Short.MAX_VALUE)
        );
        jPanel5.setLayout(jPanel5Layout);

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));

        jLabel14.setFont(new Font("Segoe UI", Font.BOLD, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("CONTACT US");
        jLabel14.setToolTipText("");

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("+51 789543");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("insta.png"))); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("twit.png"))); // NOI18N
        jLabel24.setToolTipText("");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2022-07-06 000042.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6Layout.setHorizontalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel6Layout.createSequentialGroup()
        					.addGap(19)
        					.addComponent(jLabel15))
        				.addGroup(jPanel6Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jLabel14, GroupLayout.DEFAULT_SIZE, 1123, Short.MAX_VALUE)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel23)
        			.addGap(18)
        			.addComponent(jLabel24, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel16)
        			.addGap(62))
        );
        jPanel6Layout.setVerticalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel16)
        				.addComponent(jLabel23)
        				.addComponent(jLabel24, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel6Layout.createSequentialGroup()
        					.addGap(14)
        					.addComponent(jLabel14)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jLabel15)))
        			.addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel6.setLayout(jPanel6Layout);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("MAKE A BOOKING");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("REGISTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 51, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("MAIN MENU");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton4.setBackground(new java.awt.Color(0, 51, 51));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("UPDATE A BOOKING");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton5.setBackground(new java.awt.Color(0, 51, 51));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("CANCEL A BOOKING");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton6.setBackground(new java.awt.Color(0, 51, 51));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("VIEW TICKET");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabel4.setText("PASSENGER");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 51));
        jLabel5.setText("WARNING This Domain is constantly monitored by the main server.");
        
        lblPortal = new JLabel();
        lblPortal.setVerticalAlignment(SwingConstants.TOP);
        lblPortal.setText("PORTAL");
        lblPortal.setFont(new Font("Rockwell", Font.BOLD, 36));
        
        txtrWelcomeAboardJsky = new JTextArea();
        txtrWelcomeAboardJsky.setWrapStyleWord(true);
        txtrWelcomeAboardJsky.setEditable(false);
        txtrWelcomeAboardJsky.setFont(new Font("Monospaced", Font.BOLD, 18));
        txtrWelcomeAboardJsky.setBackground(new Color(151, 190, 190));
        txtrWelcomeAboardJsky.setText("Welcome aboard JSKY! Take control of your journey with our easy-to-use interface. From booking to updates and cancellations, JSKY puts you in charge. Your smooth travel experience starts here");
        txtrWelcomeAboardJsky.setLineWrap(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4Layout.setHorizontalGroup(
        	jPanel4Layout.createParallelGroup(Alignment.TRAILING)
        		.addComponent(jPanel6, GroupLayout.DEFAULT_SIZE, 1540, Short.MAX_VALUE)
        		.addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, 1540, Short.MAX_VALUE)
        		.addGroup(jPanel4Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 556, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(974, Short.MAX_VALUE))
        		.addGroup(jPanel4Layout.createSequentialGroup()
        			.addGap(208)
        			.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel4Layout.createSequentialGroup()
        					.addComponent(jLabel4)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(lblPortal, GroupLayout.PREFERRED_SIZE, 221, GroupLayout.PREFERRED_SIZE))
        				.addComponent(txtrWelcomeAboardJsky, GroupLayout.PREFERRED_SIZE, 565, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
        			.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(74)
        			.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 255, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 255, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jButton5, GroupLayout.PREFERRED_SIZE, 255, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jButton6, GroupLayout.PREFERRED_SIZE, 255, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 255, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 255, GroupLayout.PREFERRED_SIZE))
        			.addGap(238))
        );
        jPanel4Layout.setVerticalGroup(
        	jPanel4Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel4Layout.createSequentialGroup()
        			.addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(84)
        			.addGroup(jPanel4Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel4Layout.createSequentialGroup()
        					.addGroup(jPanel4Layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jLabel4)
        						.addComponent(lblPortal, GroupLayout.PREFERRED_SIZE, 43, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE))
        					.addGroup(jPanel4Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel4Layout.createSequentialGroup()
        							.addGap(20)
        							.addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(jButton5, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(jButton6, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 48, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel4Layout.createSequentialGroup()
        							.addGap(38)
        							.addComponent(txtrWelcomeAboardJsky, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        				.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 406, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
        			.addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, 119, GroupLayout.PREFERRED_SIZE))
        		.addGroup(jPanel4Layout.createSequentialGroup()
        			.addContainerGap(679, Short.MAX_VALUE)
        			.addComponent(jLabel5)
        			.addGap(125))
        );
        jPanel4.setLayout(jPanel4Layout);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        		.addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, 1514, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(10)
        					.addComponent(jPanel4, GroupLayout.PREFERRED_SIZE, 824, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Event handler for the "Make a Booking" button.
     * Disposes of the current frame and opens a new instance of the ticket class.
     *
     * @param evt The ActionEvent generated by the button click.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        super.dispose();
        T1=new ticket();
        T1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Event handler for the "Register" button.
     * Disposes of the current frame and opens a new instance of the addCustomer class.
     *
     * @param evt The ActionEvent generated by the button click.
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        super.dispose();
        A1=new addCustomer();
        A1.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Event handler for the "Main Menu" button.
     * Disposes of the current frame and opens a new instance of the welcome class.
     *
     * @param evt The ActionEvent generated by the button click.
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        super.dispose();
        W1=new welcome();
        W1.setVisible(true);
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * Event handler for the "Update a Booking" button.
     * Disposes of the current frame and opens a new instance of the update class.
     *
     * @param evt The ActionEvent generated by the button click.
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        super.dispose();
        U1=new update();
        U1.setSize(1150,900);
        U1.setVisible(true);
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * Event handler for the "Cancel a Booking" button.
     * Disposes of the current frame and opens a new instance of the cancels class.
     *
     * @param evt The ActionEvent generated by the button click.
     */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        super.dispose();
        C1=new cancels();
        C1.setVisible(true);
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * Event handler for the "View Ticket" button.
     * Disposes of the current frame and opens a new instance of the viewTicket class.
     *
     * @param evt The ActionEvent generated by the button click.
     */
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        super.dispose();
        VT=new viewTicket();
        VT.setVisible(true);
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private welcome W1;
    private addCustomer A1;
    private update U1;
    private cancels C1;
    private ticket T1;
    private viewTicket VT;
    private JLabel lblPortal;
    private JTextArea txtrWelcomeAboardJsky;
}
