
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Represents the ticket report window of the application.
 * Displays a report of ticket information retrieved from the database.
 * Allows administrators to view a list of tickets.
 *
 * @author Imaan Ibrar
 * @version 1.0
 * @since 2023-11-21
 */
public class ticketreport extends javax.swing.JFrame {

    /**
     * Creates new form ticketreport
     */
    public ticketreport() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        LoadData();
    }
Connection con;
PreparedStatement pst;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        ticketReportTitle = new javax.swing.JLabel();
        ticketReportTitle.setForeground(new Color(255, 255, 255));
        footerPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        contactUsLabel = new javax.swing.JLabel();
        phoneNumLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSkyIcon = new javax.swing.JLabel();
        instagramIcon = new javax.swing.JLabel();
        linkedinIcon = new javax.swing.JLabel();
        basePanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        ticketReportTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        headerPanel.setBackground(new java.awt.Color(0, 102, 102));

        ticketReportTitle.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        ticketReportTitle.setText("TICKETS REPORT");
        ticketReportTitle.setToolTipText("");

        javax.swing.GroupLayout gl_headerPanel = new javax.swing.GroupLayout(headerPanel);
        gl_headerPanel.setHorizontalGroup(
        	gl_headerPanel.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, gl_headerPanel.createSequentialGroup()
        			.addContainerGap(695, Short.MAX_VALUE)
        			.addComponent(ticketReportTitle)
        			.addGap(646))
        );
        gl_headerPanel.setVerticalGroup(
        	gl_headerPanel.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_headerPanel.createSequentialGroup()
        			.addGap(19)
        			.addComponent(ticketReportTitle)
        			.addContainerGap(19, Short.MAX_VALUE))
        );
        headerPanel.setLayout(gl_headerPanel);

        footerPanel.setBackground(new java.awt.Color(0, 102, 102));

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));

        contactUsLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contactUsLabel.setForeground(new java.awt.Color(255, 255, 255));
        contactUsLabel.setText("CONTACT US");
        contactUsLabel.setToolTipText("");

        phoneNumLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        phoneNumLabel.setForeground(new java.awt.Color(255, 255, 255));
        phoneNumLabel.setText("+51 789543");

        jSkyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2022-07-06 000042.png"))); // NOI18N

        instagramIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insta.png"))); // NOI18N

        linkedinIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/twit.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(phoneNumLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(contactUsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(90, 90, 90)))
                .addComponent(jLabel21)
                .addGap(157, 157, 157)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(203, 203, 203))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(linkedinIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(instagramIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jSkyIcon)
                        .addGap(58, 58, 58))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contactUsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phoneNumLabel)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSkyIcon))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(instagramIcon)
                            .addComponent(linkedinIcon))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gl_footerPanel = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(gl_footerPanel);
        gl_footerPanel.setHorizontalGroup(
            gl_footerPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
            .addGroup(gl_footerPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gl_footerPanel.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 720, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        gl_footerPanel.setVerticalGroup(
            gl_footerPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
            .addGroup(gl_footerPanel.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gl_footerPanel.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        basePanel.setBackground(new java.awt.Color(146, 184, 184));

        backButton.setBackground(new java.awt.Color(0, 51, 51));
        backButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TicketNo", "Flight No", "Customer ID", "Class", "Price", "Seats", "Date"
            }
        ));
        ticketReportTable.setViewportView(jTable1);

        javax.swing.GroupLayout gl_basePanel = new javax.swing.GroupLayout(basePanel);
        gl_basePanel.setHorizontalGroup(
        	gl_basePanel.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_basePanel.createSequentialGroup()
        			.addContainerGap(402, Short.MAX_VALUE)
        			.addGroup(gl_basePanel.createParallelGroup(Alignment.LEADING)
        				.addGroup(Alignment.TRAILING, gl_basePanel.createSequentialGroup()
        					.addComponent(ticketReportTable, GroupLayout.PREFERRED_SIZE, 777, GroupLayout.PREFERRED_SIZE)
        					.addGap(361))
        				.addGroup(Alignment.TRAILING, gl_basePanel.createSequentialGroup()
        					.addComponent(backButton, GroupLayout.PREFERRED_SIZE, 155, GroupLayout.PREFERRED_SIZE)
        					.addGap(670))))
        );
        gl_basePanel.setVerticalGroup(
        	gl_basePanel.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_basePanel.createSequentialGroup()
        			.addGap(37)
        			.addComponent(ticketReportTable, GroupLayout.PREFERRED_SIZE, 450, GroupLayout.PREFERRED_SIZE)
        			.addGap(35)
        			.addComponent(backButton, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(52, Short.MAX_VALUE))
        );
        basePanel.setLayout(gl_basePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(footerPanel, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 1554, Short.MAX_VALUE)
        		.addComponent(basePanel, GroupLayout.DEFAULT_SIZE, 1554, Short.MAX_VALUE)
        		.addComponent(headerPanel, GroupLayout.DEFAULT_SIZE, 1554, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(headerPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(basePanel, GroupLayout.PREFERRED_SIZE, 623, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(footerPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Event handler for the "Back" button.
     * Disposes of the current frame and opens a new instance of the admindomain class.
     * @param evt The ActionEvent generated by the button click.
     * @return None.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        A1=new admindomain();
        A1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Loads data from the "ticket" table into the jTable1.
     * Uses a PreparedStatement to execute a SELECT query.
     * @return None.
     */
    public void LoadData()
    {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
             con = DriverManager.getConnection("jdbc:mysql://localhost/airline","root","1234");
             pst = con.prepareStatement("SELECT * from ticket");
             ResultSet rs = pst.executeQuery();
             
             ResultSetMetaData rsm = rs.getMetaData();
             int c;
             c = rsm.getColumnCount();
             
             DefaultTableModel Df = (DefaultTableModel)jTable1.getModel();
             Df.setRowCount(0);
             
             while(rs.next())
             {
                 Vector v2 = new Vector();
                 
                 for(int i = 1; i<= c; i ++)
                 {
                     v2.add(rs.getString("id"));
                  v2.add(rs.getString("flightid"));
                  v2.add(rs.getString("custid"));
                  v2.add(rs.getString("class"));
                  v2.add(rs.getString("price"));
                  v2.add(rs.getString("seats"));
                  v2.add(rs.getString("date"));
             
                 }
                 Df.addRow(v2);
             }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ticket.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ticket.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel ticketReportTitle;
    private javax.swing.JLabel contactUsLabel;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel phoneNumLabel;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jSkyIcon;
    private javax.swing.JLabel instagramIcon;
    private javax.swing.JLabel linkedinIcon;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel basePanel;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane ticketReportTable;
    private javax.swing.JTable jTable1;
    private admindomain A1;
    // End of variables declaration//GEN-END:variables
}
