import com.toedter.calendar.JDateChooser;

import javax.swing.*;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * This class represents a GUI application for updating airline tickets.
 * It allows users to search for existing tickets, view available flights, and
 * update ticket details.
 * The class provides functionality for changing the flight, date, class, and
 * seats for a ticket.
 *
 * @author laiba atiq
 * @version 1.0
 * @since 2022-06-12
 */
public class update extends javax.swing.JFrame {

    /**
     * Creates new form update
     */
    /**
     * Creates a new instance of the 'update' class.
     */
    public update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new JPanel();
        jScrollPane1 = new JScrollPane();
        jTable1 = new JTable();
        jPanel1 = new JPanel();
        jPanel3 = new JPanel();
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        jPanel2 = new JPanel();
        jLabel12 = new JLabel();
        jLabel13 = new JLabel();
        jLabel14 = new JLabel();
        jLabel15 = new JLabel();
        jLabel16 = new JLabel();
        jLabel17 = new JLabel();
        txtclass = new JComboBox<>();
        txtprice = new JLabel();
        txtseats = new JSpinner();
        flightno = new JLabel();
        flightnamelabel = new JLabel();
        txtdept = new JLabel();
        jButton2 = new JButton();
        jButton1 = new JButton();
        txtfirstname = new JLabel();
        txtlastname = new JLabel();
        txtpassport = new JLabel();
        jButton3 = new JButton();
        txtdepart = new JComboBox<>();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new JLabel();
        txtticketid = new JTextField();
        jButton4 = new JButton();
        jLabel1 = new JLabel();
        txtsource = new JComboBox<>();
        txtticketno = new JLabel();
        jPanel5 = new JPanel();
        jLabel4 = new JLabel();
        jPanel9 = new JPanel();
        jLabel19 = new JLabel();
        jLabel34 = new JLabel();
        jLabel35 = new JLabel();
        jLabel36 = new JLabel();
        jLabel37 = new JLabel();
        jLabel38 = new JLabel();
        jLabel39 = new JLabel();
        txtdate = new JDateChooser();

        jButton1.setEnabled(false);
        txtseats.setEnabled(false);
        txtclass.setEnabled(false);
        txtsource.setEnabled(false);
        txtdepart.setEnabled(false);
        jButton3.setEnabled(false);
        txtdate.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel9.setText("Date");

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new Color(146, 190, 190));

        jTable1.setModel(new DefaultTableModel(
                new Object[][] {
                },
                new String[] {
                        "Flight No", "Flight Name", "Source", "Departure", "DepTime", "ArrTime", "Charge"
                }));
        jTable1.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBackground(new Color(151, 190, 190));

        jPanel3.setBackground(new Color(151, 190, 190));

        jLabel6.setFont(new Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel6.setText("FirstName");

        jLabel7.setFont(new Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel7.setText("LastName");

        jLabel8.setFont(new Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel8.setText("Passportno");

        jPanel2.setBackground(new Color(151, 190, 190));

        jLabel12.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Flight no");

        jLabel13.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Filght Name");

        jLabel14.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Departure Time");

        jLabel15.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Class");

        jLabel16.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Price");

        jLabel17.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Seats");

        txtclass.setModel(new DefaultComboBoxModel<>(new String[] { "Economy", "Business" }));

        txtclass.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                txtclassStateChanged(evt);
            }
        });

        txtseats.addChangeListener(new ChangeListener() {
            public void stateChanged(ChangeEvent evt) {
                txtseatsStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel13)
                                                        .addComponent(jLabel12)
                                                        .addComponent(jLabel14)
                                                        .addComponent(jLabel15)
                                                        .addComponent(jLabel17))
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(30, 30, 30)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(flightno)
                                                                        .addComponent(flightnamelabel)
                                                                        .addComponent(txtdept)
                                                                        .addComponent(txtclass, 0, 133,
                                                                                Short.MAX_VALUE)))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(27, 27, 27)
                                                                .addComponent(txtseats,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 64,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(jLabel16)
                                        .addComponent(txtprice, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 136,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(131, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel12)
                                        .addComponent(flightno, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(flightnamelabel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(txtdept, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel15))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                jPanel2Layout.createSequentialGroup()
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtclass, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtseats, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17))));

        jButton2.setBackground(new Color(0, 51, 51));
        jButton2.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new Color(255, 255, 255));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new Color(0, 51, 51));
        jButton1.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new Color(255, 255, 255));
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel8))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel3Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(txtfirstname,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 140,
                                                                Short.MAX_VALUE)
                                                        .addComponent(txtlastname)
                                                        .addComponent(txtpassport))
                                                .addGap(129, 129, 129))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jButton1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 138,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jButton2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 134,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(txtpassport, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 403,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(204, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap(509, Short.MAX_VALUE)));

        jButton3.setBackground(new Color(0, 51, 51));
        jButton3.setForeground(new Color(255, 255, 255));
        jButton3.setText("Search");
        jButton3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtdepart.setModel(
                new DefaultComboBoxModel<>(new String[] { "Pakistan\t", "Srilanka", "Uk", "Usa", "Canada", "China" }));

        jLabel2.setFont(new Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(SwingConstants.LEFT);
        jLabel2.setText("Departure");

        jLabel3.setText("Ticket No");

        jLabel5.setFont(new Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel5.setText("Ticket No.");

        jButton4.setBackground(new Color(0, 51, 51));
        jButton4.setForeground(new Color(255, 255, 255));
        jButton4.setText("Search");
        jButton4.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel1.setText("Source");

        txtsource.setModel(
                new DefaultComboBoxModel<>(new String[] { "Pakistan", "Srilanka", "Uk", "Usa", "Canada", "Chinna" }));

        txtticketno.setFont(new Font("Tahoma", 1, 24)); // NOI18N
        txtticketno.setForeground(new Color(255, 0, 0));
        txtticketno.setText("Ticket NO");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addGroup(jPanel6Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addComponent(jLabel5)
                                                                .addGap(36, 36, 36)
                                                                .addComponent(txtticketid,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 151,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(43, 43, 43)
                                                                .addComponent(jButton4))
                                                        .addComponent(jLabel2)
                                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addGroup(jPanel6Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtdepart,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                171,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtsource,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                173,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel1))
                                                                .addGap(63, 63, 63)
                                                                .addGroup(jPanel6Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel9)
                                                                        .addComponent(txtdate,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                148,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jButton3))))
                                                .addGap(106, 106, 106)
                                                .addComponent(jLabel3))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addGroup(jPanel6Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jScrollPane1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 618,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtticketno))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(56, 56, 56)
                                                .addGroup(jPanel6Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addGap(27, 27, 27)
                                                                .addGroup(jPanel6Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel1)
                                                                        .addComponent(txtticketno)
                                                                        .addComponent(jLabel9))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel6Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtdate,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                                                .addComponent(txtsource,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(29, 29, 29)
                                                                                .addComponent(jLabel2)
                                                                                .addGap(18, 18, 18)
                                                                                .addGroup(jPanel6Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                        .addComponent(txtdepart,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(jButton3))
                                                                                .addGap(103, 103, 103)
                                                                                .addComponent(jScrollPane1,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        179,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addComponent(jLabel5))
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addGroup(jPanel6Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButton4)
                                                        .addComponent(txtticketid,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));

        jLabel4.setFont(new Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel4.setForeground(new Color(255, 255, 255));
        jLabel4.setText("UPDATE MY FLIGHT");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap(394, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(399, 399, 399)));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel4)
                                .addContainerGap(32, Short.MAX_VALUE)));

        jPanel9.setBackground(new Color(0, 102, 102));

        jLabel19.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new Color(255, 255, 255));
        jLabel19.setText("CONTACT US");
        jLabel19.setToolTipText("");

        jLabel34.setFont(new Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel34.setForeground(new Color(255, 255, 255));
        jLabel34.setText("+51 789543");

        jLabel37.setIcon(new ImageIcon(getClass().getResource("/Screenshot 2022-07-06 000042.png"))); // NOI18N

        jLabel38.setIcon(new ImageIcon(getClass().getResource("/insta.png"))); // NOI18N

        jLabel39.setIcon(new ImageIcon(getClass().getResource("/twit.png"))); // NOI18N

        GroupLayout jPanel9Layout = new GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addComponent(jLabel34)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED,
                                                        GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addComponent(jLabel19, GroupLayout.DEFAULT_SIZE,
                                                        GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(90, 90, 90)))
                                .addComponent(jLabel35)
                                .addGap(157, 157, 157)
                                .addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addComponent(jLabel36)
                                                .addGap(203, 203, 203))
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addComponent(jLabel39)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel38)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 44,
                                                        Short.MAX_VALUE)
                                                .addComponent(jLabel37)
                                                .addGap(58, 58, 58)))));
        jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel19)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel35)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addComponent(jLabel34)
                                .addContainerGap(31, Short.MAX_VALUE))
                        .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGroup(jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel37))
                                        .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addGroup(
                                                        jPanel9Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel38)
                                                                .addComponent(jLabel39))))
                                .addGap(0, 18, Short.MAX_VALUE)));

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jPanel9, GroupLayout.DEFAULT_SIZE,
                                                        GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 387, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, 1156,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(388, Short.MAX_VALUE))));
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                        GroupLayout.PREFERRED_SIZE)
                                .addGap(619, 619, 619)
                                .addComponent(jPanel9, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
                                        GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, 619,
                                                GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(96, Short.MAX_VALUE))));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handle a change in the 'class' combo box selection.
     *
     * @param evt The ActionEvent triggered by the user's action.
     */
    private void txtclassStateChanged(ActionEvent evt) {
        int seats = (int) txtseats.getValue();
        String classSeat = (String) txtclass.getSelectedItem();

        int price_used;
        if (price == 0) {
            if (oldclass.equals("Business"))
                price_used = (int) ((oldprice) / (Integer.parseInt(oldseats) * 1.5));
            else
                price_used = (int) ((oldprice) / Integer.parseInt(oldseats));
        } else
            price_used = price;

        if (!txtprice.getText().equals("") && seats > 0 && seats < 10) {

            if (classSeat.equals("Business")) {
                double bill = 1.5 * price_used * seats;
                txtprice.setText(String.valueOf((int) bill));
            } else {
                double bill = price_used * seats;
                txtprice.setText(String.valueOf((int) bill));
            }
        }
    }

    /**
     * Handle a change in the 'seats' spinner state.
     *
     * @param evt The ChangeEvent triggered by the user's action.
     */
    private void txtseatsStateChanged(ChangeEvent evt) {
        int seats = (int) txtseats.getValue();
        String classSeat = (String) txtclass.getSelectedItem();

        int price_used;
        if (price == 0) {
            if (oldclass.equals("Business"))
                price_used = (int) ((oldprice) / (Integer.parseInt(oldseats) * 1.5));
            else
                price_used = (int) ((oldprice) / Integer.parseInt(oldseats));
        } else
            price_used = price;

        if (!txtprice.getText().equals("") && seats > 0 && seats < 10) {

            if (classSeat.equals("Business")) {
                double bill = 1.5 * price_used * seats;
                txtprice.setText(String.valueOf((int) bill));
            } else {
                double bill = price_used * seats;
                txtprice.setText(String.valueOf((int) bill));
            }
        }
    }

    Connection con;
    PreparedStatement pst;

    /**
     * Handle a mouse click event on the flight selection table.
     *
     * @param evt The MouseEvent triggered by the mouse click.
     */
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        DefaultTableModel Df = (DefaultTableModel) jTable1.getModel();

        int selectIndex = jTable1.getSelectedRow();

        price = Integer.parseInt((String) Df.getValueAt(selectIndex, 6));

        flightno.setText(Df.getValueAt(selectIndex, 0).toString());
        flightnamelabel.setText(Df.getValueAt(selectIndex, 1).toString());
        txtdept.setText(Df.getValueAt(selectIndex, 4).toString());
        txtprice.setText(Df.getValueAt(selectIndex, 6).toString());
    }// GEN-LAST:event_jTable1MouseClicked

    /**
     * Handle the button click event to search for available flights based on source
     * and destination.
     *
     * @param evt The ActionEvent triggered by the button click.
     * @throws ClassNotFoundException if the MySQL JDBC driver class is not found
     * @throws SQLException           if a database access error occurs
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        String source = txtsource.getSelectedItem().toString().trim();
        String depart = txtdepart.getSelectedItem().toString().trim();

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "1234");
            pst = con.prepareStatement("SELECT * from flight WHERE source = ? and depart = ?");

            pst.setString(1, source);
            pst.setString(2, depart);
            ResultSet rs = pst.executeQuery();

            ResultSetMetaData rsm = rs.getMetaData();
            int c;
            c = rsm.getColumnCount();

            DefaultTableModel Df = (DefaultTableModel) jTable1.getModel();
            jTable1.setDefaultEditor(Object.class, null);
            Df.setRowCount(0);

            while (rs.next()) {
                arrivaltime = rs.getString("arrtime");
                flightname = rs.getString("flightname");
                departTime = rs.getString("deptime");
                sourceCity = rs.getString("source");
                departCity = rs.getString("depart");
                Vector v2 = new Vector();

                for (int i = 1; i <= c; i++) {
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("flightname"));
                    v2.add(rs.getString("source"));
                    v2.add(rs.getString("depart"));
                    // v2.add(rs.getString("date"));
                    v2.add(rs.getString("deptime"));
                    v2.add(rs.getString("arrtime"));
                    v2.add(rs.getString("flightcharge"));
                }

                Df.addRow(v2);

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ticket.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_jButton3ActionPerformed

    /**
     * Handle the button click event to search for a ticket by ID.
     *
     * @param evt The ActionEvent triggered by the button click.
     * @throws ClassNotFoundException if the MySQL JDBC driver class is not found
     * @throws SQLException           if a database access error occurs
     */

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String id = txtticketid.getText();
        txtticketno.setText(id);

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "1234");
            pst = con.prepareStatement("select * from ticket where id = ?");
            pst.setString(1, id);
            ResultSet rs = pst.executeQuery();

            if (rs.next() == false) {
                JOptionPane.showMessageDialog(this, "Record not Found");
            } else {
                oldclass = rs.getString("class");
                oldseats = rs.getString("seats");
                String fname = rs.getString("firstname");
                String lname = rs.getString("lastname");
                departTime = rs.getString("deptime");
                arrivaltime = rs.getString("arrtime");
                String passport = rs.getString("passport");
                flightname = rs.getString("flightname");
                oldprice = rs.getInt("price");
                sourceCity = rs.getString("source");
                departCity = rs.getString("depart");
                flightid = rs.getString("flightid");
                custid = rs.getString("custid");
                Date date = rs.getDate("date");

                txtseats.setValue(Integer.parseInt(oldseats));
                txtdate.setDate(date);
                txtclass.setSelectedItem(oldclass);
                txtfirstname.setText(fname.trim());
                txtlastname.setText(lname.trim());
                flightno.setText(flightid);
                flightnamelabel.setText(flightname.trim());
                txtpassport.setText(passport.trim());
                txtdept.setText(departTime.trim());
                txtprice.setText(String.valueOf(oldprice));
                txtsource.setSelectedItem(sourceCity);
                txtdepart.setSelectedItem(departCity);

                jButton4.setEnabled(false);
                txtticketid.setEditable(false);

                jButton1.setEnabled(true);
                txtseats.setEnabled(true);
                txtclass.setEnabled(true);
                txtsource.setEnabled(true);
                txtdepart.setEnabled(true);
                jButton3.setEnabled(true);
                txtdate.setEnabled(true);

            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_jButton4ActionPerformed

    /**
     * Handle the button click event to update a ticket with new details.
     *
     * @param evt The ActionEvent triggered by the button click.
     * @throws ClassNotFoundException if the MySQL JDBC driver class is not found
     * @throws SQLException           if a database access error occurs
     * @throws NullPointerException   if the date is not entered
     */

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String ticketid = txtticketno.getText();
        String flightid = flightno.getText();
        String flightclass = txtclass.getSelectedItem().toString().trim();
        String seats = txtseats.getValue().toString();

        DateFormat da = new SimpleDateFormat("yyyy-MM-dd");

        if (seats.equals("") || Integer.parseInt(seats) < 1 || Integer.parseInt(seats) > 9) {
            JOptionPane.showMessageDialog(this, "Seats must be between 1-9");
        } else {
            try {
                String date = da.format(txtdate.getDate());

                SimpleDateFormat df = new SimpleDateFormat("yyyy");
                String year = df.format(txtdate.getDate());
                int yr = Integer.parseInt(year);
                if (!(yr == 2022)) {
                    JOptionPane.showMessageDialog(this, "Can only book for the current year");
                } else {

                    Class.forName("com.mysql.cj.jdbc.Driver");
                    con = DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "1234");

                    PreparedStatement preparedStmt = con.prepareStatement(
                            "UPDATE ticket SET flightid=?,flightname=?,custid=?,firstname=?,lastname=?,passport=?,class=?,price=?,seats=?,date=?,deptime=?,arrtime=?,source=?,depart=? WHERE id = ?");
                    preparedStmt.setString(15, ticketid);

                    preparedStmt.setString(1, flightid);
                    preparedStmt.setString(2, flightname);
                    preparedStmt.setString(3, custid);
                    preparedStmt.setString(4, txtfirstname.getText());
                    preparedStmt.setString(5, txtlastname.getText());
                    preparedStmt.setString(6, txtpassport.getText());
                    preparedStmt.setString(7, flightclass);
                    preparedStmt.setString(8, txtprice.getText());

                    preparedStmt.setString(9, seats);
                    preparedStmt.setString(10, date);
                    preparedStmt.setString(11, departTime);
                    preparedStmt.setString(12, arrivaltime);
                    preparedStmt.setString(13, sourceCity);
                    preparedStmt.setString(14, departCity);

                    // execute the java preparedstatement
                    preparedStmt.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Ticket Updated");
                    this.dispose();
                    B1 = new bill(custid, ticketid);
                    B1.setVisible(true);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(addflight.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(this, "Please enter the Date");
            }
        }
    }

    // GEN-LAST:event_jButton1ActionPerformed

    /**
     * Handle the button click event to return to the customer domain.
     *
     * @param evt The ActionEvent triggered by the button click.
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        C1 = new cusdomain();
        C1.setVisible(true);
    }// GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel txtfirstname;
    private javax.swing.JLabel txtlastname;
    private javax.swing.JLabel txtpassport;
    private javax.swing.JLabel flightno;
    private javax.swing.JLabel flightnamelabel;
    private javax.swing.JLabel txtdept;
    private javax.swing.JComboBox<String> txtclass;
    private javax.swing.JTextField txtticketid;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JComboBox<String> txtdepart;
    private javax.swing.JLabel txtprice;
    private javax.swing.JSpinner txtseats;
    private javax.swing.JComboBox<String> txtsource;
    private javax.swing.JLabel txtticketno;
    private String departTime, arrivaltime, sourceCity, departCity, flightname, flightid;
    private int price, oldprice;
    private String oldclass, oldseats, custid;
    private bill B1;
    private cusdomain C1;
    // End of variables declaration//GEN-END:variables
}